#!/usr/bin/env bash
set -euo pipefail

# SAPL dry-run demo: previews an allowlisted PR from a suggested task.
# Prereqs:
#   - Frontend server running and reachable (default http://localhost:3000)
#   - Server started with AUTO_PR_ENABLED=1 (preview is guarded by this flag)
# Usage:
#   FRONTEND_PORT=3000 bash forgekeeper/scripts/sapl_demo.sh [file] [label]
# Example:
#   AUTO_PR_ENABLED=1 FRONTEND_PORT=3000 bash forgekeeper/scripts/sapl_demo.sh README.md docs

PORT=${FRONTEND_PORT:-3000}
FILE=${1:-README.md}
LABEL=${2:-docs}

TITLE="[docs] Update docs via SAPL preview"
BODY="Generated by TGT/SAPL demo at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
APPEND=$'\n### Self‑Improvement\nThis line was proposed by TGT (demo).'

payload=$(cat <<JSON
{
  "title": ${TITLE@Q},
  "body": ${BODY@Q},
  "files": [${FILE@Q}],
  "labels": [${LABEL@Q}],
  "edits": [{"path": ${FILE@Q}, "appendText": ${APPEND@Q}}]
}
JSON
)

echo "POST http://localhost:${PORT}/api/auto_pr/preview"
set +e
resp=$(curl -s -w "\n%{http_code}" -H 'Content-Type: application/json' -X POST \
  --data "$payload" \
  "http://localhost:${PORT}/api/auto_pr/preview")
code=$(echo "$resp" | tail -n1)
body=$(echo "$resp" | sed -n '1,$p' | sed '$d')
set -e

if [[ "$code" != "200" ]]; then
  echo "Preview failed (HTTP $code). Is AUTO_PR_ENABLED=1 for the server?" >&2
  echo "$body"
  exit 1
fi

if command -v jq >/dev/null 2>&1; then
  echo "$body" | jq '{ok, preview: {files: .preview.files, labels: .preview.labels, appendPreviews: (.preview.appendPreviews|length)}}'
else
  echo "$body"
fi

echo "Done. This was a dry-run preview (no PR created)."

